### ISSUE TITLE
Failed linkify install ?

### ISSUE THREAD

**Issue by lapineige** [bonfire-networks/linkify#1]
When trying to run `just config` here: https://github.com/YunoHost-Apps/bonfire_ynh/blob/cleaning/scripts/install#LL80C15-L80C48

I have this:
```
* Updating linkify (https://github.com/bonfire-networks/linkify - origin/master)
fatal: reference is not a tree: e15ff9c5f885c65177c42a5b99669423370d8967
** (Mix) Command "git --git-dir=.git checkout --quiet e15ff9c5f885c65177c42a5b99669423370d8967" failed
```
What's going wrong ?

**Comment by mayel** [comment]
oh looks like that commit may have been the victim of a rebase: https://github.com/bonfire-networks/linkify/commit/e15ff9c5f885c65177c42a5b99669423370d8967
I've just pushed a commit to bonfire-app which hopefully references the correct commit of the dependency...

**Comment by lapineige** [comment]
Removing the line from mix.lock makes it recreate it with the latest commit for your information (and it works apparently).

**Comment by mayel** [comment]
great 👍
